services:

  server:
    platform: linux/arm64
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./back:/app
    env_file:
      - ./back/.env.dev
    depends_on:
      - dbPostgres
  
  dbPostgres:
    platform: linux/arm64
    image: postgres:13-alpine
    env_file:
      - ./back/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  pgadmin:
    platform: linux/arm64
    image: dpage/pgadmin4
    env_file:
      - ./back/.env.dev
    ports:
      - "5050:80"
    depends_on:
      dbPostgres:
        condition: service_healthy

volumes:
  postgres_data:
  
    
