# Use an ARM-based Node.js image
FROM --platform=linux/arm64 node:18


# Set environment variables
# ENV NODE_ENV=production

# Set the working directory in the container
WORKDIR /app/back

# Copy package.json and pnpm-lock.yaml
COPY package*.json pnpm-lock.yaml /app/back/

# Install pnpm globally
RUN npm install -g pnpm

# Install dependencies
RUN pnpm install

# Install build tools, rebuild bcrypt, and clean up
# RUN pnpm rebuild bcrypt --update-binary


# Install nodemon globally
RUN npm install -g nodemon

# Copy the rest of the application source code
COPY . .

# Expose the application port
EXPOSE 3001

# Define the command to run the application
CMD [ "pnpm", "run", "dev" ]
